<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GatewaysTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('gateways')->delete();

        DB::table('gateways')->insert(array(
            0 =>
            array(
                'alias' => 'Paypal',
                'code' => 101,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"paypal_email":{"title":"PayPal Email","global":true,"value":"------------"}}',
                'id' => 1,
                'name' => 'Paypal',
                'status' => 1,
                'supported_currencies' => '{"AUD":"AUD","BRL":"BRL","CAD":"CAD","CZK":"CZK","DKK":"DKK","EUR":"EUR","HKD":"HKD","HUF":"HUF","INR":"INR","ILS":"ILS","JPY":"JPY","MYR":"MYR","MXN":"MXN","TWD":"TWD","NZD":"NZD","NOK":"NOK","PHP":"PHP","PLN":"PLN","GBP":"GBP","RUB":"RUB","SGD":"SGD","SEK":"SEK","CHF":"CHF","THB":"THB","USD":"$"}',
                'updated_at' => '2022-11-27 07:27:36',
            ),
            1 =>
            array(
                'alias' => 'PerfectMoney',
                'code' => 102,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"passphrase":{"title":"ALTERNATE PASSPHRASE","global":true,"value":"------------"},"wallet_id":{"title":"PM Wallet","global":false,"value":""}}',
                'id' => 2,
                'name' => 'Perfect Money',
                'status' => 1,
                'supported_currencies' => '{"USD":"$","EUR":"\\u20ac"}',
                'updated_at' => '2022-11-27 07:27:57',
            ),
            2 =>
            array(
                'alias' => 'Stripe',
                'code' => 103,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"secret_key":{"title":"Secret Key","global":true,"value":"------------"},"publishable_key":{"title":"PUBLISHABLE KEY","global":true,"value":"------------"}}',
                'id' => 3,
                'name' => 'Stripe Hosted',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","SGD":"SGD"}',
                'updated_at' => '2022-11-27 07:28:11',
            ),
            3 =>
            array(
                'alias' => 'Skrill',
                'code' => 104,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"pay_to_email":{"title":"Skrill Email","global":true,"value":"------------"},"secret_key":{"title":"Secret Key","global":true,"value":"---"}}',
                'id' => 4,
                'name' => 'Skrill',
                'status' => 1,
                'supported_currencies' => '{"AED":"AED","AUD":"AUD","BGN":"BGN","BHD":"BHD","CAD":"CAD","CHF":"CHF","CZK":"CZK","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","HRK":"HRK","HUF":"HUF","ILS":"ILS","INR":"INR","ISK":"ISK","JOD":"JOD","JPY":"JPY","KRW":"KRW","KWD":"KWD","MAD":"MAD","MYR":"MYR","NOK":"NOK","NZD":"NZD","OMR":"OMR","PLN":"PLN","QAR":"QAR","RON":"RON","RSD":"RSD","SAR":"SAR","SEK":"SEK","SGD":"SGD","THB":"THB","TND":"TND","TRY":"TRY","TWD":"TWD","USD":"USD","ZAR":"ZAR","COP":"COP"}',
                'updated_at' => '2022-11-27 07:28:05',
            ),
            4 =>
            array(
                'alias' => 'Paytm',
                'code' => 105,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"MID":{"title":"Merchant ID","global":true,"value":"------------"},"merchant_key":{"title":"Merchant Key","global":true,"value":"------------"},"WEBSITE":{"title":"Paytm Website","global":true,"value":"DIYtestingweb"},"INDUSTRY_TYPE_ID":{"title":"Industry Type","global":true,"value":"Retail"},"CHANNEL_ID":{"title":"CHANNEL ID","global":true,"value":"WEB"},"transaction_url":{"title":"Transaction URL","global":true,"value":"https:\\/\\/pguat.paytm.com\\/oltp-web\\/processTransaction"},"transaction_status_url":{"title":"Transaction STATUS URL","global":true,"value":"https:\\/\\/pguat.paytm.com\\/paytmchecksum\\/paytmCallback.jsp"}}',
                'id' => 5,
                'name' => 'PayTM',
                'status' => 1,
                'supported_currencies' => '{"AUD":"AUD","ARS":"ARS","BDT":"BDT","BRL":"BRL","BGN":"BGN","CAD":"CAD","CLP":"CLP","CNY":"CNY","COP":"COP","HRK":"HRK","CZK":"CZK","DKK":"DKK","EGP":"EGP","EUR":"EUR","GEL":"GEL","GHS":"GHS","HKD":"HKD","HUF":"HUF","INR":"INR","IDR":"IDR","ILS":"ILS","JPY":"JPY","KES":"KES","MYR":"MYR","MXN":"MXN","MAD":"MAD","NPR":"NPR","NZD":"NZD","NGN":"NGN","NOK":"NOK","PKR":"PKR","PEN":"PEN","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SGD":"SGD","ZAR":"ZAR","KRW":"KRW","LKR":"LKR","SEK":"SEK","CHF":"CHF","THB":"THB","TRY":"TRY","UGX":"UGX","UAH":"UAH","AED":"AED","GBP":"GBP","USD":"USD","VND":"VND","XOF":"XOF"}',
                'updated_at' => '2022-11-27 07:27:55',
            ),
            5 =>
            array(
                'alias' => 'Payeer',
                'code' => 106,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => '{"status":{"title": "Status URL","value":"ipn.Payeer"}}',
                'form_id' => 0,
                'gateway_parameters' => '{"merchant_id":{"title":"Merchant ID","global":true,"value":"------------"},"secret_key":{"title":"Secret key","global":true,"value":"------------"}}',
                'id' => 6,
                'name' => 'Payeer',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","EUR":"EUR","RUB":"RUB"}',
                'updated_at' => '2022-11-27 07:27:33',
            ),
            6 =>
            array(
                'alias' => 'Paystack',
                'code' => 107,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => '{"callback":{"title": "Callback URL","value":"ipn.Paystack"},"webhook":{"title": "Webhook URL","value":"ipn.Paystack"}}
',
                'form_id' => 0,
                'gateway_parameters' => '{"public_key":{"title":"Public key","global":true,"value":"------------"},"secret_key":{"title":"Secret key","global":true,"value":"------------"}}',
                'id' => 7,
                'name' => 'PayStack',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","NGN":"NGN"}',
                'updated_at' => '2022-11-27 07:27:45',
            ),
            7 =>
            array(
                'alias' => 'Voguepay',
                'code' => 108,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"merchant_id":{"title":"MERCHANT ID","global":true,"value":"------------"}}',
                'id' => 8,
                'name' => 'VoguePay',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","GBP":"GBP","EUR":"EUR","GHS":"GHS","NGN":"NGN","ZAR":"ZAR"}',
                'updated_at' => '2022-11-27 07:28:29',
            ),
            8 =>
            array(
                'alias' => 'Flutterwave',
                'code' => 109,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"public_key":{"title":"Public Key","global":true,"value":"----------------"},"secret_key":{"title":"Secret Key","global":true,"value":"-----------------------"},"encryption_key":{"title":"Encryption Key","global":true,"value":"------------------"}}',
                'id' => 9,
                'name' => 'Flutterwave',
                'status' => 1,
                'supported_currencies' => '{"BIF":"BIF","CAD":"CAD","CDF":"CDF","CVE":"CVE","EUR":"EUR","GBP":"GBP","GHS":"GHS","GMD":"GMD","GNF":"GNF","KES":"KES","LRD":"LRD","MWK":"MWK","MZN":"MZN","NGN":"NGN","RWF":"RWF","SLL":"SLL","STD":"STD","TZS":"TZS","UGX":"UGX","USD":"USD","XAF":"XAF","XOF":"XOF","ZMK":"ZMK","ZMW":"ZMW","ZWD":"ZWD"}',
                'updated_at' => '2021-06-05 11:37:45',
            ),
            9 =>
            array(
                'alias' => 'Razorpay',
                'code' => 110,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"key_id":{"title":"Key Id","global":true,"value":"------------"},"key_secret":{"title":"Key Secret ","global":true,"value":"------------"}}',
                'id' => 10,
                'name' => 'RazorPay',
                'status' => 1,
                'supported_currencies' => '{"INR":"INR"}',
                'updated_at' => '2022-11-27 07:28:02',
            ),
            10 =>
            array(
                'alias' => 'StripeJs',
                'code' => 111,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"secret_key":{"title":"Secret Key","global":true,"value":"------------"},"publishable_key":{"title":"PUBLISHABLE KEY","global":true,"value":"------------"}}',
                'id' => 11,
                'name' => 'Stripe Storefront',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","SGD":"SGD"}',
                'updated_at' => '2022-11-27 07:28:17',
            ),
            11 =>
            array(
                'alias' => 'Instamojo',
                'code' => 112,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API KEY","global":true,"value":"------------"},"auth_token":{"title":"Auth Token","global":true,"value":"------------"},"salt":{"title":"Salt","global":true,"value":"------------"}}',
                'id' => 12,
                'name' => 'Instamojo',
                'status' => 1,
                'supported_currencies' => '{"INR":"INR"}',
                'updated_at' => '2022-11-27 07:27:13',
            ),
            12 =>
            array(
                'alias' => 'Blockchain',
                'code' => 501,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 1,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"------------"},"xpub_code":{"title":"XPUB CODE","global":true,"value":"------------"}}',
                'id' => 13,
                'name' => 'Blockchain',
                'status' => 1,
                'supported_currencies' => '{"BTC":"BTC"}',
                'updated_at' => '2022-11-27 07:26:42',
            ),
            13 =>
            array(
                'alias' => 'Coinpayments',
                'code' => 503,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 1,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"public_key":{"title":"Public Key","global":true,"value":"---------------"},"private_key":{"title":"Private Key","global":true,"value":"------------"},"merchant_id":{"title":"Merchant ID","global":true,"value":"------------"}}',
                'id' => 15,
                'name' => 'CoinPayments',
                'status' => 1,
                'supported_currencies' => '{"BTC":"Bitcoin","BTC.LN":"Bitcoin (Lightning Network)","LTC":"Litecoin","CPS":"CPS Coin","VLX":"Velas","APL":"Apollo","AYA":"Aryacoin","BAD":"Badcoin","BCD":"Bitcoin Diamond","BCH":"Bitcoin Cash","BCN":"Bytecoin","BEAM":"BEAM","BITB":"Bean Cash","BLK":"BlackCoin","BSV":"Bitcoin SV","BTAD":"Bitcoin Adult","BTG":"Bitcoin Gold","BTT":"BitTorrent","CLOAK":"CloakCoin","CLUB":"ClubCoin","CRW":"Crown","CRYP":"CrypticCoin","CRYT":"CryTrExCoin","CURE":"CureCoin","DASH":"DASH","DCR":"Decred","DEV":"DeviantCoin","DGB":"DigiByte","DOGE":"Dogecoin","EBST":"eBoost","EOS":"EOS","ETC":"Ether Classic","ETH":"Ethereum","ETN":"Electroneum","EUNO":"EUNO","EXP":"EXP","Expanse":"Expanse","FLASH":"FLASH","GAME":"GameCredits","GLC":"Goldcoin","GRS":"Groestlcoin","KMD":"Komodo","LOKI":"LOKI","LSK":"LSK","MAID":"MaidSafeCoin","MUE":"MonetaryUnit","NAV":"NAV Coin","NEO":"NEO","NMC":"Namecoin","NVST":"NVO Token","NXT":"NXT","OMNI":"OMNI","PINK":"PinkCoin","PIVX":"PIVX","POT":"PotCoin","PPC":"Peercoin","PROC":"ProCurrency","PURA":"PURA","QTUM":"QTUM","RES":"Resistance","RVN":"Ravencoin","RVR":"RevolutionVR","SBD":"Steem Dollars","SMART":"SmartCash","SOXAX":"SOXAX","STEEM":"STEEM","STRAT":"STRAT","SYS":"Syscoin","TPAY":"TokenPay","TRIGGERS":"Triggers","TRX":" TRON","UBQ":"Ubiq","UNIT":"UniversalCurrency","USDT":"Tether USD (Omni Layer)","USDT.BEP20":"Tether USD (BSC Chain)","USDT.ERC20":"Tether USD (ERC20)","USDT.TRC20":"Tether USD (Tron/TRC20)","VTC":"Vertcoin","WAVES":"Waves","XCP":"Counterparty","XEM":"NEM","XMR":"Monero","XSN":"Stakenet","XSR":"SucreCoin","XVG":"VERGE","XZC":"ZCoin","ZEC":"ZCash","ZEN":"Horizen"}',
                'updated_at' => '2022-11-27 07:27:03',
            ),
            14 =>
            array(
                'alias' => 'CoinpaymentsFiat',
                'code' => 504,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"merchant_id":{"title":"Merchant ID","global":true,"value":"------------"}}',
                'id' => 16,
                'name' => 'CoinPayments Fiat',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","CLP":"CLP","CNY":"CNY","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","ISK":"ISK","JPY":"JPY","KRW":"KRW","NZD":"NZD","PLN":"PLN","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD"}',
                'updated_at' => '2022-11-27 07:27:06',
            ),
            15 =>
            array(
                'alias' => 'Coingate',
                'code' => 505,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"------------"}}',
                'id' => 17,
                'name' => 'Coingate',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","EUR":"EUR"}',
                'updated_at' => '2022-11-27 07:26:58',
            ),
            16 =>
            array(
                'alias' => 'CoinbaseCommerce',
                'code' => 506,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => '{"endpoint":{"title": "Webhook Endpoint","value":"ipn.CoinbaseCommerce"}}',
                'form_id' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"------------"},"secret":{"title":"Webhook Shared Secret","global":true,"value":"------------"}}',
                'id' => 18,
                'name' => 'Coinbase Commerce',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","EUR":"EUR","JPY":"JPY","GBP":"GBP","AUD":"AUD","CAD":"CAD","CHF":"CHF","CNY":"CNY","SEK":"SEK","NZD":"NZD","MXN":"MXN","SGD":"SGD","HKD":"HKD","NOK":"NOK","KRW":"KRW","TRY":"TRY","RUB":"RUB","INR":"INR","BRL":"BRL","ZAR":"ZAR","AED":"AED","AFN":"AFN","ALL":"ALL","AMD":"AMD","ANG":"ANG","AOA":"AOA","ARS":"ARS","AWG":"AWG","AZN":"AZN","BAM":"BAM","BBD":"BBD","BDT":"BDT","BGN":"BGN","BHD":"BHD","BIF":"BIF","BMD":"BMD","BND":"BND","BOB":"BOB","BSD":"BSD","BTN":"BTN","BWP":"BWP","BYN":"BYN","BZD":"BZD","CDF":"CDF","CLF":"CLF","CLP":"CLP","COP":"COP","CRC":"CRC","CUC":"CUC","CUP":"CUP","CVE":"CVE","CZK":"CZK","DJF":"DJF","DKK":"DKK","DOP":"DOP","DZD":"DZD","EGP":"EGP","ERN":"ERN","ETB":"ETB","FJD":"FJD","FKP":"FKP","GEL":"GEL","GGP":"GGP","GHS":"GHS","GIP":"GIP","GMD":"GMD","GNF":"GNF","GTQ":"GTQ","GYD":"GYD","HNL":"HNL","HRK":"HRK","HTG":"HTG","HUF":"HUF","IDR":"IDR","ILS":"ILS","IMP":"IMP","IQD":"IQD","IRR":"IRR","ISK":"ISK","JEP":"JEP","JMD":"JMD","JOD":"JOD","KES":"KES","KGS":"KGS","KHR":"KHR","KMF":"KMF","KPW":"KPW","KWD":"KWD","KYD":"KYD","KZT":"KZT","LAK":"LAK","LBP":"LBP","LKR":"LKR","LRD":"LRD","LSL":"LSL","LYD":"LYD","MAD":"MAD","MDL":"MDL","MGA":"MGA","MKD":"MKD","MMK":"MMK","MNT":"MNT","MOP":"MOP","MRO":"MRO","MUR":"MUR","MVR":"MVR","MWK":"MWK","MYR":"MYR","MZN":"MZN","NAD":"NAD","NGN":"NGN","NIO":"NIO","NPR":"NPR","OMR":"OMR","PAB":"PAB","PEN":"PEN","PGK":"PGK","PHP":"PHP","PKR":"PKR","PLN":"PLN","PYG":"PYG","QAR":"QAR","RON":"RON","RSD":"RSD","RWF":"RWF","SAR":"SAR","SBD":"SBD","SCR":"SCR","SDG":"SDG","SHP":"SHP","SLL":"SLL","SOS":"SOS","SRD":"SRD","SSP":"SSP","STD":"STD","SVC":"SVC","SYP":"SYP","SZL":"SZL","THB":"THB","TJS":"TJS","TMT":"TMT","TND":"TND","TOP":"TOP","TTD":"TTD","TWD":"TWD","TZS":"TZS","UAH":"UAH","UGX":"UGX","UYU":"UYU","UZS":"UZS","VEF":"VEF","VND":"VND","VUV":"VUV","WST":"WST","XAF":"XAF","XAG":"XAG","XAU":"XAU","XCD":"XCD","XDR":"XDR","XOF":"XOF","XPD":"XPD","XPF":"XPF","XPT":"XPT","YER":"YER","ZMW":"ZMW","ZWL":"ZWL"}

',
                'updated_at' => '2022-11-27 07:26:53',
            ),
            17 =>
            array(
                'alias' => 'PaypalSdk',
                'code' => 113,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"clientId":{"title":"Paypal Client ID","global":true,"value":"------------"},"clientSecret":{"title":"Client Secret","global":true,"value":"------------"}}',
                'id' => 24,
                'name' => 'Paypal Express',
                'status' => 1,
                'supported_currencies' => '{"AUD":"AUD","BRL":"BRL","CAD":"CAD","CZK":"CZK","DKK":"DKK","EUR":"EUR","HKD":"HKD","HUF":"HUF","INR":"INR","ILS":"ILS","JPY":"JPY","MYR":"MYR","MXN":"MXN","TWD":"TWD","NZD":"NZD","NOK":"NOK","PHP":"PHP","PLN":"PLN","GBP":"GBP","RUB":"RUB","SGD":"SGD","SEK":"SEK","CHF":"CHF","THB":"THB","USD":"$"}',
                'updated_at' => '2022-11-27 07:27:40',
            ),
            18 =>
            array(
                'alias' => 'StripeV3',
                'code' => 114,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => '{"webhook":{"title": "Webhook Endpoint","value":"ipn.StripeV3"}}',
                'form_id' => 0,
                'gateway_parameters' => '{"secret_key":{"title":"Secret Key","global":true,"value":"------------"},"publishable_key":{"title":"PUBLISHABLE KEY","global":true,"value":"------------"},"end_point":{"title":"End Point Secret","global":true,"value":"------------"}}',
                'id' => 25,
                'name' => 'Stripe Checkout',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","SGD":"SGD"}',
                'updated_at' => '2022-11-27 07:28:25',
            ),
            19 =>
            array(
                'alias' => 'Mollie',
                'code' => 115,
                'created_at' => '2019-09-14 13:14:22',
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"mollie_email":{"title":"Mollie Email ","global":true,"value":"------------"},"api_key":{"title":"API KEY","global":true,"value":"------------"}}',
                'id' => 27,
                'name' => 'Mollie',
                'status' => 1,
                'supported_currencies' => '{"AED":"AED","AUD":"AUD","BGN":"BGN","BRL":"BRL","CAD":"CAD","CHF":"CHF","CZK":"CZK","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","HRK":"HRK","HUF":"HUF","ILS":"ILS","ISK":"ISK","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD","USD":"USD","ZAR":"ZAR"}',
                'updated_at' => '2022-11-27 07:27:26',
            ),
            20 =>
            array(
                'alias' => 'Cashmaal',
                'code' => 116,
                'created_at' => NULL,
                'crypto' => 0,
                'description' => NULL,
                'extra' => '{"webhook":{"title": "IPN URL","value":"ipn.Cashmaal"}}',
                'form_id' => 0,
                'gateway_parameters' => '{"web_id":{"title":"Web Id","global":true,"value":"------------"},"ipn_key":{"title":"IPN Key","global":true,"value":"------------"}}',
                'id' => 30,
                'name' => 'Cashmaal',
                'status' => 1,
                'supported_currencies' => '{"PKR":"PKR","USD":"USD"}',
                'updated_at' => '2022-11-27 07:26:47',
            ),
            21 =>
            array(
                'alias' => 'MercadoPago',
                'code' => 119,
                'created_at' => NULL,
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"access_token":{"title":"Access Token","global":true,"value":"------------"}}',
                'id' => 36,
                'name' => 'Mercado Pago',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","NOK":"NOK","PLN":"PLN","SEK":"SEK","AUD":"AUD","NZD":"NZD"}',
                'updated_at' => '2022-11-27 07:27:21',
            ),
            22 =>
            array(
                'alias' => 'Authorize',
                'code' => 120,
                'created_at' => NULL,
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"login_id":{"title":"Login ID","global":true,"value":"------------"},"transaction_key":{"title":"Transaction Key","global":true,"value":"------------"}}',
                'id' => 37,
                'name' => 'Authorize.net',
                'status' => 1,
                'supported_currencies' => '{"USD":"USD","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","NOK":"NOK","PLN":"PLN","SEK":"SEK","AUD":"AUD","NZD":"NZD"}',
                'updated_at' => '2022-11-27 07:26:37',
            ),
            23 =>
            array(
                'alias' => 'NMI',
                'code' => 121,
                'created_at' => NULL,
                'crypto' => 0,
                'description' => NULL,
                'extra' => NULL,
                'form_id' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"------------"}}',
                'id' => 46,
                'name' => 'NMI',
                'status' => 1,
                'supported_currencies' => '{"AED":"AED","ARS":"ARS","AUD":"AUD","BOB":"BOB","BRL":"BRL","CAD":"CAD","CHF":"CHF","CLP":"CLP","CNY":"CNY","COP":"COP","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","IDR":"IDR","ILS":"ILS","INR":"INR","JPY":"JPY","KRW":"KRW","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PEN":"PEN","PHP":"PHP","PLN":"PLN","PYG":"PYG","RUB":"RUB","SEC":"SEC","SGD":"SGD","THB":"THB","TRY":"TRY","TWD":"TWD","USD":"USD","ZAR":"ZAR"}',
                'updated_at' => '2022-11-27 07:27:29',
            ),
        ));
    }
}
